// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for this platform - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPTXGoyHVEp1oV8_TWTbeIR-cAaW8080A',
    appId: '1:324129360218:web:684473dc56e9bca3b28b63',
    messagingSenderId: '324129360218',
    projectId: 'open-trivia-king',
    authDomain: 'open-trivia-king.firebaseapp.com',
    storageBucket: 'open-trivia-king.appspot.com',
    measurementId: 'G-32MHCRVH5B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDO78gdKLx_K6gAId2GZcoffhSgzmILAHA',
    appId: '1:324129360218:android:d8cdd3b4f55eb51bb28b63',
    messagingSenderId: '324129360218',
    projectId: 'open-trivia-king',
    storageBucket: 'open-trivia-king.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1yMIURwOuKsl2HtPQ53Jss59MHHSWdhA',
    appId: '1:324129360218:ios:072421adaeeb724db28b63',
    messagingSenderId: '324129360218',
    projectId: 'open-trivia-king',
    storageBucket: 'open-trivia-king.appspot.com',
    iosClientId: '324129360218-arcdgsi4da53hss4s8ul0jjnpajsubt0.apps.googleusercontent.com',
    iosBundleId: 'com.admijw.opentriviaking',
  );
}
